spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cineferchodb}
    username: ${SPRING_DATASOURCE_USERNAME:cinefercho}
    password: ${SPRING_DATASOURCE_PASSWORD:cinefercho}
    driver-class-name: org.postgresql.Driver
