spring:
  application:
    name: cinefercho

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cineferchodb}
    username: ${SPRING_DATASOURCE_USERNAME:cinefercho}
    password: ${SPRING_DATASOURCE_PASSWORD:cinefercho}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

cinefercho:
  jwt:
    secret: CineferchoJwtSecretKeyForHS256AlgorithmMustBeLongEnough2026!
    expiration-ms: 86400000
    client-expiration-ms: 120000
