spring:
  application:
    name: cinefercho
  profiles:
    default: h2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

cinefercho:
  jwt:
    secret: CineferchoJwtSecretKeyForHS256AlgorithmMustBeLongEnough2026!
    expiration-ms: 86400000
    client-expiration-ms: 120000

tmdb:
  api:
    key: ${TMDB_API_KEY:}
    url: https://api.themoviedb.org/3
